services:
  mysql:
    image: mysql:8.0  # 你可以改为 mysql:5.7 或其他版本
    restart: always  # 让 MySQL 容器自动重启
    environment:
      MYSQL_ROOT_PASSWORD: root  # root 用户密码
      MYSQL_DATABASE: demo_db  # 默认创建的数据库
      MYSQL_USER: user  # 普通用户
      MYSQL_PASSWORD: password  # 普通用户密码
    ports:
      - "3306:3306"  # 把容器内的 3306 端口映射到本机
    networks:
      - mynetwork
    volumes:
      - mysql_data:/var/lib/mysql  # 数据持久化

  flask_app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
    volumes:
      - .:/app
    depends_on:
      - mysql  # 让 Flask 依赖 MySQL
    networks:
      - mynetwork

networks:
  mynetwork:

volumes:
  mysql_data:


