services:
  backend:
    build: ./backend
    restart: always
    ports:
      - "5000:5000"
  
    depends_on:
      - mysql
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=123456
      - DB_NAME=demo_db
      - DB_PORT=3306
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app

  mysql:  
    image: mysql:8.0                   
    restart: always
    command: --init-file /docker-entrypoint-initdb.d/init.sql
    ports:
      - "33306:3306"
    logging:
      driver: 'json-file'
      options:
        max-size: '5g'
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: demo_db
    volumes:
      - "./mysql/data:/var/lib/mysql" 
      - "./mysql/config:/etc/mysql/conf.d" 
      - "./init.sql:/docker-entrypoint-initdb.d/init.sql"
