NACOS_SERVER = "127.0.0.1:8848"
NACOS_NAMESPACE = "public"
NACOS_SERVICE_NAME = "analysis-service"
NACOS_GROUP = "DEFAULT_GROUP"
NACOS_DATA_ID = "event-mysql-config"

SERVICE_PORT = 8000
GOOGLE_API_KEY="AIzaSyAuEfY6IzV2n2wSHiOUw9RQ1l8ZtM6Y8So"